site_name: "Shopware Hilfe - Plugin: Optimierte Lieferzeiten"
repo_url: https://github.com/AREA-NET-GmbH-Shopware-Agentur/shopware6-plugin-better-delivery-time
theme:
  name: 'material'
  language: 'de'
  favicon: 'images/areanet-favicon.ico'
  logo: 'images/areanet-logo.png'
  palette:
    scheme: default
    primary: custom
extra_css:
  - stylesheets/areanet.css
plugins:
  - tags
  - mkdocs-versioning:
      version: 1.0.0
extra:
  version:
    provider: mike
nav:
  - Beschreibung: index.md
  - Download und Installation: installation.md
  - Konfiguration: konfiguration.md
  - E-Mail Snippets: email.md
  - Support: support.md
